services:
  mongo:
    image: mongo
    container_name: senpai-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 10101010
    ports:
      - "27017:27017"
    volumes:
      - senpai-db:/data/db
  redis:
    image: redis:alpine
    container_name: senpai-redis
    restart: always
    volumes:
      - senpai-redis:/data
  api: 
    build: .
    container_name: senpai-api
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - redis

volumes:
  senpai-db:
    driver: local
  senpai-redis:
    driver: local
