import type { Mission } from "@/models";

export const STATIC_MISSIONS: readonly Mission[] = [
  {
    id: "daily_checkin",
    title: "Presença Diária",
    description: "Abra o Senpai e confira suas novidades do dia.",
    goal: 1,
    metric: "app_checkin",
    reward: { xp: 40, petals: 5 },
    active: true,
  },
  {
    id: "create_sticker",
    title: "Criar Figurinha",
    description: "Crie pelo menos 1 figurinha no editor hoje.",
    goal: 1,
    metric: "stickers_created",
    reward: { xp: 120, petals: 20 },
    active: true,
  },
  {
    id: "favorite_pack",
    title: "Apoiar a Comunidade",
    description: "Adicione 1 pacote público aos seus favoritos.",
    goal: 1,
    metric: "packs_favorited",
    reward: { xp: 80, petals: 10 },
    active: true,
  },
  {
    id: "morning_greeting",
    title: "Bom Dia, Senpai!",
    description: "Inicie o seu dia conferindo os novos destaques do aplicativo.",
    goal: 1,
    metric: "app_checkin",
    reward: { xp: 45, petals: 6 },
    active: true,
  },
  {
    id: "daily_radar",
    title: "Radar Ativado",
    description: "Abra o catálogo para ficar por dentro das figurinhas em alta.",
    goal: 1,
    metric: "app_checkin",
    reward: { xp: 50, petals: 7 },
    active: true,
  },
  {
    id: "quick_glance",
    title: "Espiadinha Rápida",
    description: "Dê uma olhada rápida na sua coleção e nas novidades.",
    goal: 1,
    metric: "app_checkin",
    reward: { xp: 35, petals: 5 },
    active: true,
  },
  {
    id: "loyal_visitor",
    title: "Membro Assíduo",
    description: "Marque presença e mantenha sua rotina no Senpai ativa.",
    goal: 1,
    metric: "app_checkin",
    reward: { xp: 55, petals: 8 },
    active: true,
  },
  {
    id: "first_spark",
    title: "Primeira Faísca",
    description: "Dê asas à imaginação e conclua 1 nova figurinha no editor.",
    goal: 1,
    metric: "stickers_created",
    reward: { xp: 110, petals: 18 },
    active: true,
  },
  {
    id: "creative_duo",
    title: "Dupla Criativa",
    description: "Crie pelo menos 2 figurinhas originais durante o ciclo de hoje.",
    goal: 2,
    metric: "stickers_created",
    reward: { xp: 210, petals: 35 },
    active: true,
  },
  {
    id: "meme_craftsman",
    title: "Artesão de Memes",
    description: "Elabore 2 figurinhas expressivas para usar com os amigos.",
    goal: 2,
    metric: "stickers_created",
    reward: { xp: 225, petals: 38 },
    active: true,
  },
  {
    id: "daily_creator_trio",
    title: "Trinca Inspirada",
    description: "Alcance a meta de 3 figurinhas criadas no editor hoje.",
    goal: 3,
    metric: "stickers_created",
    reward: { xp: 320, petals: 55 },
    active: true,
  },
  {
    id: "quota_master",
    title: "Mestre da Cota",
    description: "Aproveite ao máximo e crie 3 figurinhas no dia.",
    goal: 3,
    metric: "stickers_created",
    reward: { xp: 340, petals: 60 },
    active: true,
  },
  {
    id: "sticker_enthusiast",
    title: "Ritmo Frenético",
    description: "Crie 4 figurinhas empolgantes no decorrer do dia.",
    goal: 4,
    metric: "stickers_created",
    reward: { xp: 440, petals: 75 },
    active: true,
  },
  {
    id: "sticker_factory",
    title: "Fábrica de Figurinhas",
    description: "Alcance o expressivo marco de 5 figurinhas criadas hoje.",
    goal: 5,
    metric: "stickers_created",
    reward: { xp: 550, petals: 95 },
    active: true,
  },
  {
    id: "prolific_artist",
    title: "Artista Prolífico",
    description: "Desenvolva 6 figurinhas no editor em um único dia.",
    goal: 6,
    metric: "stickers_created",
    reward: { xp: 660, petals: 115 },
    active: true,
  },
  {
    id: "sticker_artisan",
    title: "Mão na Massa",
    description: "Produza 8 figurinhas estilizadas para alimentar os seus chats.",
    goal: 8,
    metric: "stickers_created",
    reward: { xp: 880, petals: 155 },
    active: true,
  },
  {
    id: "editor_legend",
    title: "Lenda do Editor",
    description: "Crie 10 figurinhas fantásticas e mostre todo o seu talento.",
    goal: 10,
    metric: "stickers_created",
    reward: { xp: 1150, petals: 200 },
    active: true,
  },
  {
    id: "divine_creator",
    title: "Divindade da Criação",
    description: "Atinja o impressionante recorde de 15 figurinhas feitas no dia.",
    goal: 15,
    metric: "stickers_created",
    reward: { xp: 1750, petals: 300 },
    active: true,
  },
  {
    id: "taste_explorer",
    title: "Garimpeiro Casual",
    description: "Descubra e favorite 1 pacote novo da comunidade.",
    goal: 1,
    metric: "packs_favorited",
    reward: { xp: 75, petals: 9 },
    active: true,
  },
  {
    id: "pair_of_favorites",
    title: "Seleção Dupla",
    description: "Adicione 2 pacotes públicos à sua lista de favoritos.",
    goal: 2,
    metric: "packs_favorited",
    reward: { xp: 140, petals: 18 },
    active: true,
  },
  {
    id: "sticker_hunter",
    title: "Caçador de Pacotes",
    description: "Encontre e favorite 2 pacotes que chamaram sua atenção hoje.",
    goal: 2,
    metric: "packs_favorited",
    reward: { xp: 150, petals: 20 },
    active: true,
  },
  {
    id: "curator_apprentice",
    title: "Curador Aprendiz",
    description: "Favorite 3 pacotes públicos criados por outros autores.",
    goal: 3,
    metric: "packs_favorited",
    reward: { xp: 215, petals: 30 },
    active: true,
  },
  {
    id: "treasure_seeker",
    title: "Caçador de Tesouros",
    description: "Explore a comunidade e favorite 3 coleções imperdíveis.",
    goal: 3,
    metric: "packs_favorited",
    reward: { xp: 230, petals: 32 },
    active: true,
  },
  {
    id: "community_booster",
    title: "Apoiador Dedicado",
    description: "Fortaleça a comunidade adicionando 4 pacotes aos favoritos.",
    goal: 4,
    metric: "packs_favorited",
    reward: { xp: 295, petals: 42 },
    active: true,
  },
  {
    id: "gallery_collector",
    title: "Colecionador Diário",
    description: "Marque 5 pacotes do catálogo como favoritos ao longo do dia.",
    goal: 5,
    metric: "packs_favorited",
    reward: { xp: 380, petals: 55 },
    active: true,
  },
  {
    id: "pack_admirer",
    title: "Admirador do Feed",
    description: "Apoie os criadores favoritando 6 pacotes públicos hoje.",
    goal: 6,
    metric: "packs_favorited",
    reward: { xp: 465, petals: 68 },
    active: true,
  },
  {
    id: "avid_collector",
    title: "Colecionador Fervoroso",
    description: "Favorite 7 pacotes e monte uma seleção de peso para o WhatsApp.",
    goal: 7,
    metric: "packs_favorited",
    reward: { xp: 545, petals: 80 },
    active: true,
  },
  {
    id: "pack_guardian",
    title: "Guardião de Pacotes",
    description: "Favorite 8 coleções para enriquecer a sua biblioteca pessoal.",
    goal: 8,
    metric: "packs_favorited",
    reward: { xp: 640, petals: 95 },
    active: true,
  },
  {
    id: "elite_curator",
    title: "Curador de Elite",
    description: "Alcance o marco de 10 pacotes favoritados na comunidade.",
    goal: 10,
    metric: "packs_favorited",
    reward: { xp: 810, petals: 120 },
    active: true,
  },
  {
    id: "senpai_patron",
    title: "Mecenas do Senpai",
    description: "Favorite 12 pacotes e apoie em peso os criadores da plataforma.",
    goal: 12,
    metric: "packs_favorited",
    reward: { xp: 980, petals: 145 },
    active: true,
  },
] as const;
